### ISSUE TITLE
Issue with logging in

### ISSUE THREAD

**Issue by Diothememer** [sandarshsridhar/wiz-spotify-connected#25]
Hey im having an Issue when i try to login to the local host its giving me 

INVALID_CLIENT: Invalid client error

![image](https://github.com/sandarshsridhar/wiz-spotify-connected/assets/65994930/3bef18eb-fdc7-445d-96fc-2b3db45facba)

**Comment by sandarshsridhar** [comment]
The app is probably unable to access the .env file.  Another user also reported this issue to me a couple of months ago. In this case, a simple fix would be to set up the Spotify configuration directly in the config file. 

All you have to do is replace the values of clientID and clientSecret with your actual values here instead of doing it in the .env file: https://github.com/sandarshsridhar/wiz-spotify-connected/blob/main/src/configs/spotify-config.ts#L6-L7
     
```typescript
    clientId: 'YOUR_ACTUAL_CLIENT_ID',
    clientSecret: 'YOUR_ACTUAL_CLIENT_SECRET'
```
Lemme know if this works for you.

**Comment by Diothememer** [comment]
thanks it worked perfectly!, i have a few thoughts about it, The delay is noticeable but ig that's the limitations or working with such bulbs and then Colors not switching quickly enough even in party mode!, 

Loved It eitherway great work!

**Comment by sandarshsridhar** [comment]
Great! I have only noticed the delay in the newer bulbs (Oct 21 and later). Because I have around 24 bulbs, 22 of which are from before Oct 21 and they sync to signals sent by the app seamlessly and super quickly. But the other 2 tend to be a bit sluggish and behave as though they are playing a catch-up game. There must have been some changes in the components of these bulbs because I see the delay even from the Wiz (both v1 and v2) app. I hope they fix the issue in the newer batches.

Anyway, I am glad the fix worked for you.
