### ISSUE TITLE
Adjust Tempo?

### ISSUE THREAD

**Issue by konrad51** [sandarshsridhar/wiz-spotify-connected#31]
Program seems to work well, but has kind of a pulsating effect that doesn't quite sync with the music . I am assuming this is the tempo. Is there a way to reduce or eliminate this and just leave the color changing effect? Thanks.

**Comment by sandarshsridhar** [comment]
@konrad51, You cannot adjust the tempo because the tempo is the number of beats per minute in a song. Have you tried running the app in `calm` mode? If not, give it a try: [calm](https://github.com/sandarshsridhar/wiz-spotify-connected#calm). It does significantly slow down the pace of the changing lights.

If you are noticing out-of-sync light changes, then I am afraid your bulbs might be from a bad batch. I have 2 of those too and it's super annoying because they respond way slower than my other ones do. 

On a side note, I will consider adding the option to only change the lights and not alternate between low and high brightness. This will of course be optional. So, stay tuned.

I hope this helps.

**Comment by konrad51** [comment]
Thanks for responding. I did try the calm mode and I like it very much. ( and I like the program overall very much !).  I use a couple of other programs that react to music with the Wiz bulbs ( LedFx and OpenRGB with Keyboard Visualizer) but it seems they respond more to the volume of the music more than anything else and they use the sound output of the computer. The option you are considering sounds interesting. Keep up the good work ! Thanks again.

**Comment by sandarshsridhar** [comment]
Thank you! Yeah, the idea was to have the lights sync to not just the music but also in a way that is very organic. Hence, I considered the pitch, loudness, beats, and several other components to achieve it. Syncing to Spotify with their API makes it super easy to do this exact thing, and as an added benefit, you can run this app on a computer in a completely different room and it would still work because the bulbs wouldn't rely on the volume from that device. 

I am finishing up the user-controllable pop effect (only changing lights and not alternating brightness levels). So, you will soon be able to enjoy the app without the pulse effect :)

I am going to close this issue as the answer seems to have helped. Thanks again and cheers!
